enum UserEventType {
  ACCOUNT_LOGIN(10),
  ACCOUNT_LOGIN_FAILURE(11),
  ACCOUNT_LOGOUT(20),
  ACCOUNT_OPENING(30),
  ACCOUNT_UPDATE(40),
  ACCOUNT_ONBOARDING(50),
  FACIAL_RECOGNITION(60),
  FINANCIAL_TRANSACTION(70),
  TRANSFER_BETWEEN_ACCOUNTS(80),
  CREDIT_APPLICATION(90),
  FINANCIAL_SERVICE_REQUEST(100),
  NON_FINANCIAL_SERVICE_REQUEST(110),
  PASSWORD_CHANGE(120),
  OTHER(130),
  AUTHENTICATION(140);

  const UserEventType(this.value);
  final int value;
}